version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "13:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: ws
    versions:
    - 7.4.2
    - 7.4.3
    - 7.4.4
  - dependency-name: opusscript
    versions:
    - 0.0.7
